### ISSUE TITLE
Пол

### ISSUE THREAD

**Issue by Gimaevazat** [bugaevm/flappy#5]
Пол != лава, почему при касании шарика пола игра заканчивается. Это не удобно, ткв начале игры хотелось бы не напрягаться, и чтобы шарик тупо катился по полу

**Comment by bugaevm** [comment]
Таковы правила игры. Увы, в реальной жизни правило "зочем напрягаца если можно не напрягаца" не всегда работает, так и в этой игре. Кстати, для облегчения жизни игроку в самом начале игры шарик подпрыгивает сам, что убийственно упрощает игру.
